### ISSUE TITLE
trouble finding test in v1.0.2

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/pyt#32]
So I've got a structure like this:

```
./
    foo_test.py
    foo/
        __init__.py
```

and if I run:

    $ pyt2 foo.ClassPrefix.func_suffix

it doesn't find the test, in fact, it doesn't even see the `foo_test.py` module, it goes right into the `foo` package and then can't find any tests.

**Comment by Jaymon** [comment]
Another similar error:

with a structure like:

```
./
    foo_test/
        __init__.py
        bar_test.py
    foo/
        __init__.py
```

if you do:

    $ pyt2 foo.bar.ClassPrefix.func_suffix

You'll get an error:

```
[W] Could not find a module path with bar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyt/path.py", line 508, in paths
    path = self._find_module_path(basedir, module_name)
  File "/usr/local/lib/python2.7/site-packages/pyt/path.py", line 444, in _find_module_path
    raise IOError("Could not find a module path with {}".format(modname))
IOError: Could not find a module path with bar
```

but doing:

    $ pyt2 foo_test.bar.ClassPrefix.func_suffix

gets rid of the printed warning
