### ISSUE TITLE
AttributeError: '_ErrorHolder' object has no attribute '_testMethodName'

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/pyt#35]
Not sure how this pops up but it does when running all the tests in testdata:

```
Traceback (most recent call last):
  File ".../bin/pyt2", line 11, in <module>
    sys.exit(console())
  File ".../python2.7/site-packages/pyt/__main__.py", line 23, in console
    main(module=None)
  File ".../python2.7/site-packages/pyt/tester.py", line 285, in __init__
    super(TestProgram, self).__init__(**kwargs)
  File ".../python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File ".../python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File ".../python2.7/site-packages/pyt/tester.py", line 248, in run
    self.stream.writeln(testpath(testcase))
  File ".../python2.7/site-packages/pyt/utils.py", line 19, in testpath
    method_name = test._testMethodName
AttributeError: '_ErrorHolder' object has no attribute '_testMethodName'
```

When running:

```
$ pyt2 testdata_test -d
```

info: 

```
$ pyt2 --version
pyt2 1.0.4, Python 2.7.15
```

**Comment by Jaymon** [comment]
I think I might've been using an old version, it looks like this has been fixed in the latest versions of pyt

**Comment by Jaymon** [comment]
I haven't seen this error in 5 years so I'm finally closing this
